[directories]
input = "/home/teol/github/MotionPhotoMuxer-HEIC/test/icloud"
output = "/home/teol/github/MotionPhotoMuxer-HEIC/test/"
[options]
# 매칭되지 않는 파일을 출력 디렉토리의 'other_files' 폴더로 이동하시겠습니까
move_other_images = true
# 매칭되는 MOV/MP4 파일이 없어도 모든 HEIC 파일을 JPEG로 변환하시겠습니까?
convert_all_heic = true
# 매칭되는 MOV/MP4 파일이 있든 없든 변환된 HEIC 파일을 삭제하시겠습니까?
delete_converted = true
# 원본 HEIC 및 MOV/MP4 파일을 삭제하시겠습니까?
delete_original = true

